apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ninh-ingress
  namespace: model-serving
spec:
  ingressClassName: nginx
  rules:
  - host: ninhmlops01.com
    http:
      paths:
      - path: /service
        pathType: Prefix
        backend:
          service:
            name: loan-prediction-service
            port:
              number: 80